"""Golden test: one small fixed-seed corpus against committed expectations.

The unit tests check invariants; this checks the actual bytes. A change to the
renderer, the paraphrase pass or the sidecar format shows up here as a diff on a
file a human wrote, which is the point - the expectation lives outside the
generator and cannot be regenerated by rebuilding the corpus.

Refreshing it is a deliberate act:

    python -m tests.golden.corpus.refresh      # prints the new expected.yaml
"""

from __future__ import annotations

from pathlib import Path

import yaml

from corpus.generator.build import build_items, load_specs, self_check
from corpus.generator.paraphrase import DeterministicParaphraser
from engine.config_loader import ConfigBundle

GOLDEN_DIR = Path(__file__).parent / "golden" / "corpus"
SCENARIO_DIR = GOLDEN_DIR / "scenarios"
EXPECTED_PATH = GOLDEN_DIR / "expected.yaml"
GOLDEN_SEED = 7


def _built(seed: int = GOLDEN_SEED) -> dict[str, dict[str, object]]:
    items = build_items(
        load_specs(SCENARIO_DIR), seed=seed, paraphraser=DeterministicParaphraser()
    )
    return {
        item.item_id: {"labels": item.labels, "payload_sha256": item.sha256()}
        for item in items
    }


def test_golden_corpus_matches_the_committed_expectation() -> None:
    expected = yaml.safe_load(EXPECTED_PATH.read_text(encoding="utf-8"))
    assert expected["seed"] == GOLDEN_SEED
    assert _built() == expected["items"]


def test_golden_corpus_still_passes_the_self_check(config: ConfigBundle) -> None:
    items = build_items(
        load_specs(SCENARIO_DIR),
        seed=GOLDEN_SEED,
        paraphraser=DeterministicParaphraser(),
    )
    self_check(items, config)


def test_a_different_seed_produces_a_different_corpus() -> None:
    """Determinism is per seed, not by accident of everything being constant."""
    other = _built(seed=8)
    assert {item_id: entry["payload_sha256"] for item_id, entry in other.items()} != {
        item_id: entry["payload_sha256"] for item_id, entry in _built().items()
    }
    assert [entry["labels"] for entry in other.values()] == [
        entry["labels"] for entry in _built().values()
    ], "surface variation must not touch the labels"
